name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      env:
        SCOPE_DSN: ${{ secrets.SCOPE_DSN}} 
      run: make test
        
    - name: Build Binaries
      run: env VERSION_STRING=${{ github.sha }} make -j 3 build-all
    
    - name: Build Latest
      run: env VERSION_STRING=${{ github.sha }} make latest
      

